version: "3.4"

networks:
  crayon_network:
    driver: bridge

services:
  mariadb:
    container_name: docker-mariadb
    image: mariadb:10.11.2
    networks:
      - crayon_network
    restart: always
    ports:
      - 3307:3306
    environment:
      - MARIADB_ROOT_PASSWORD=qwuiercxzvnm
      - MARIADB_DATABASE=crayon
      - MARIADB_USER=dev
      - MARIADB_PASSWORD=se7enngiths
      - TZ=Asia/Seoul mariad

  mongodb:
    image: mongo:6
    container_name: mongodb
    networks:
      - crayon_network
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=se7enngiths
      - MONGO_INITDB_DATABASE=crayon

  redis:
    image: redis:7
    container_name: redis
    networks:
      - crayon_network
    restart: always
    ports:
      - 6363:6379
    command: redis-server --requirepass 1q2w3e4r --port 6379